### PR TITLE
New roadmap

### PR DESCRIPTION
**Pull request by ayhankuru**
complete turkish roadmap

https://github.com/iojs/iojs-tr/issues/46

### CODE REVIEW

**Comment by ayhankuru** [comment]
@mikeal review this?

**Comment by mikeal** [comment]
Just let me know when the translation is reviewed by someone who knows turkish and I'll merge it :)

**Comment by ayhankuru** [comment]
@iojs/iojs-tr Arkadaşlar biriniz onaylarsa sevinicem

**Comment by KiPSOFT** [comment]
+1 :wave:

**Comment by ayhankuru** [comment]
@mikeal Everything looks okay ? https://github.com/iojs/roadmap/pull/48#issuecomment-98982530

**Pull request merged**
