### PR TITLE
Remove Working Group info

### PR DESCRIPTION
**Pull request by williamkapke**
See: https://github.com/nodejs/CTC/issues/16

This is the minimum change. What happens to the future of this repo can be another issue.

PLEASE NOTE: Not many people have access to merge this- so if YOU are one of the few people this will wait on YOU!

/cc @nodejs/ctc

### CODE REVIEW

**Review by Trott — APPROVED** [review]
LGTM although I think we need to do more than just this. If nothing else, put a big bold sentence at the top explaining that the working group has run its course and that people should look at the node-eps, NG, and CTC repos to get an idea of where Node.js is going. I'm OK with landing that as a separate PR though, as it might be the subject of bike-shedding.

**Comment by bnoordhuis** [comment]
I agree with @Trott.  I'd replace the README with short message explaining that this WG has been retired, links to other repos optional.

**Comment by williamkapke** [comment]
ROADMAP.md has been completely removed now. If you have the commit bit, please complete this PR.

Ref: https://github.com/nodejs/node/pull/11556

**Comment by williamkapke** [comment]
Also, please update the repo description.

Currently says "A place to discuss the Node.js roadmap"

**Pull request merged**
